config/routes.rb
SociaLoginRails::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/terms"
  get "pages/welcome"
  get "pages/landing"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users

  root :to => 'pages#landing'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user

	after_create :fetch_details



	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.username = facebook_data['username']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :email
  mount_uploader :image, ImageUploader
  has_many :authorizations

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.name = auth.info.name
       user.email = auth.info.email
       if auth.provider == "twitter" 
         user.save(:validate => false) 
       else
         user.save
       end
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	def all
		p env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "You are in..!!! Go to edit profile to see the status for the accounts"
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def welcome
  end

  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]


  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  def index
    @users = User.all
  end

  # PATCH/PUT /users/1
  def update
    # 2015-07-23 RICHARD: Updated to use strong parameters
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

    # 2015-07-23 RICHARD: Added to implement strong parameters
    def user_params
      params.require(:user).permit(:name, :user, :about)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SociaLoginRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a href="../" class="navbar-brand">Social Login</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">DropDown <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="themes">
              <li><a tabindex="-1" href="/">Default</a></li>
              <li class="divider"></li>
              <li><a tabindex="-1" href="#/">Item 1</a></li>
              <li><a tabindex="-1" href="#/">Item 2</a></li>
              <li><a tabindex="-1" href="#/">Item 3</a></li>
              <li><a tabindex="-1" href="#/">Item 4</a></li>
              <li><a tabindex="-1" href="#/">Item 5</a></li>
              <li><a tabindex="-1" href="#/">Item 6</a></li>

            </ul>
          </li>
          <li>
            <a href="">Help</a>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>


  <div class="container">
   <div class="page-header" id="banner">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/pages/landing.html.erb
<h1 style="color:green">Read me please....!!!</h1>
<h2>Sample Application showing Social login Integration with Rails</h2>
<p>This is a demo for the Social login with Twitter + Facebook + Linkedin + Github + Google + Devise</p>
<p>Also If user is logged in that case he can link his other social accounts too. To test out the functionality of connecting other social account. Go to edit profile once you are logged in by clicking on your name in header and check status of logged in accounts and you can also link the account which are not yet connected. Click on those urls to connect those social networks</p>
<p><i>There are lot of commented out gems in the Gemfile. I will recommend you to check out them too. They are one of the most common gems that I use in my various projects.</i></p>
<p style="color:red">No spam will be sent on any of your social network. No posting ever. No emails ever. I promise :)</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<% ['facebook', 'twitter', 'github', 'linkedin', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
	  <%= (image_tag @user.image_url(:thumb).to_s) %>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>